// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFal9cT3m_vjkqRyrnNuvwvP9TXy5AEDY',
    appId: '1:689589782059:web:fafed05313119676f90c6e',
    messagingSenderId: '689589782059',
    projectId: 'bookrent-18af7',
    authDomain: 'bookrent-18af7.firebaseapp.com',
    storageBucket: 'bookrent-18af7.appspot.com',
    measurementId: 'G-36F2WTPRQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiIQriJE320HNdpmFA6UJRmTz83QaoUFQ',
    appId: '1:689589782059:android:88400dd19bd0ba59f90c6e',
    messagingSenderId: '689589782059',
    projectId: 'bookrent-18af7',
    storageBucket: 'bookrent-18af7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBse_bffW7Nju3cjws_5LNFn1lE9eEd274',
    appId: '1:689589782059:ios:327e48152ae7d06bf90c6e',
    messagingSenderId: '689589782059',
    projectId: 'bookrent-18af7',
    storageBucket: 'bookrent-18af7.appspot.com',
    iosBundleId: 'com.example.kitaab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBse_bffW7Nju3cjws_5LNFn1lE9eEd274',
    appId: '1:689589782059:ios:33f91309ce3b757df90c6e',
    messagingSenderId: '689589782059',
    projectId: 'bookrent-18af7',
    storageBucket: 'bookrent-18af7.appspot.com',
    iosBundleId: 'com.example.kitaab.RunnerTests',
  );
}
